### ISSUE TITLE
abourt database script

### ISSUE THREAD

**Issue by peerct** [Guthius/softlexdental#1]
hi,i am studying OpenDental,your work is great,but i don't found your db script,is it open source?

**Comment by Guthius** [comment]
Hi, yes it is, Here's the latest dump of the db schema:

[SDental_2019_01_06.zip](https://github.com/Guthius/softlexdental/files/3694387/SDental_2019_01_06.zip)

**Comment by peerct** [comment]
@Guthius thank you very much!
